swagger: '2.0'
info:
  description: Dados até D-1 de todas as compras e vendas (ativos listados) do investidor.
  version: '1.0'
  title: B3 Investidor - Negociação de Ativos
schemes:
  - https
basePath: /api/assets-trading/v2
host: Caminho_backend
tags:
  - name: Asset Trading
paths:
  '/investors/{documentNumber}':
    get:
      tags:
        - Asset Trading
      summary: >-
        Dados até D-1 de todas as compras e vendas (ativos listados) do
        investidor.
      operationId: AssetTradingGet
      produces:
        - application/json
      parameters:
        - in: query
          name: page
          type: integer
          description: >-
            Number of the page being requested (the value of the first page is
            1).
          required: false
        - in: path
          name: documentNumber
          type: string
          maxLength: 14
          description: Número do documento
          required: true
        - in: query
          name: referenceStartDate
          type: string
          format: date
          description: Data inicial do período de consulta da informação
          required: true
        - in: query
          name: referenceEndDate
          type: string
          format: date
          description: Data fim do período de consulta da informação
          required: true
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/AssetTradingyRsp'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/Errors'
        '429':
          description: Too Many Requests
        '500':
          description: Internal server error
        '503':
          description: Service Unavailable
definitions:
  AssetTrading:
    type: object
    properties:
      tickerSymbol:
        type: string
        maxLength: 35
        description: >-
          Código que identifica um instrumento negociado/registrado em bolsa de
          valores. O símbolo é uma forma curta e conveniente de identificar um
          instrumento.
        example: XXX
      side:
        type: string
        enum:
          - compra
          - venda
        maxLength: 6
        description: Tipo de movimento. - Compra - Venda
        example: XXX
      marketName:
        type: string
        maxLength: 35
        description: |-
          Nome do mercado
          Dominio Mercado a vista Derivativos 
        example: XXX
      expirationDate:
        type: string
        format: date
        description: Data de vencimento
        example: '2020-01-01'
      participantName:
        type: string
        maxLength: 120
        description: Nome do participante (corretora)
        example: XXX
      participantDocumentNumber:
        type: string
        maxLength: 14
        description: Participant document number
        example: null
      tradeQuantity:
        type: number
        description: Quantidade total negociada
        example: 10
      priceValue:
        type: number
        description: Preço do ativo
        example: 1
      grossAmount:
        type: number
        description: Quantidade total negociada
        example: '10,00'
    required:
      - tickerSymbol
      - side
      - marketName
      - participantName
      - participantDocumentNumber
      - tradeQuantity
  Data:
    type: object
    properties:
      periods:
        $ref: '#/definitions/Period'
  Link:
    type: object
    properties:
      self:
        type: string
        description: Current page link
        example: null
      first:
        type: string
        description: First page link
        example: null
      prev:
        type: string
        description: Next page link
        example: null
      next:
        type: string
        description: Next page link
        example: null
      last:
        type: string
        description: Last page link
        example: null
    required:
      - self
  PeriodList:
    type: object
    properties:
      referenceDate:
        type: string
        format: date
        description: Data de referência da informação
        example: '2020-01-01'
      buyTotal:
        type: number
        description: Somatório do valor financeiro de todas as negociações de compra
        example: '100,50'
      sellTotal:
        type: number
        description: Somatório do valor financeiro de todas as negociações de venda
        example: '200,10'
      assetTradings:
        type: array
        items:
          $ref: '#/definitions/AssetTrading'
    required:
      - referenceDate
  Period:
    type: object
    properties:
      documentNumber:
        type: string
        maxLength: 14
        description: 'Número do documento '
        example: 00123456789
      referenceStartDate:
        type: string
        format: date
        description: Data inicial do período de consulta da informação
        example: '2020-01-01'
      referenceEndDate:
        type: string
        format: date
        description: Data fim do período de consulta da informação
        example: '2020-02-01'
      periodLists:
        type: array
        items:
          $ref: '#/definitions/PeriodList'
    required:
      - documentNumber
      - referenceStartDate
      - referenceEndDate
  Errors:
    type: object
    properties:
      Errors:
        type: array
        items:
          $ref: '#/definitions/Error'
  Error:
    type: object
    properties:
      code:
        type: string
        description: Business error code.
        example: null
      message:
        type: string
        description: Brief business error message
        example: null
    required:
      - code
      - message
  AssetTradingyRsp:
    type: object
    properties:
      data:
        $ref: '#/definitions/Data'
      Links:
        $ref: '#/definitions/Link'
    required:
      - Links